loadPythonModules  <- function () {
    check = system.file ("python", "check.py", package="DNAshapeR")
    hello = system.file ("python", "hello.py", package="DNAshapeR")
    autoconvert = system.file ("python", "autoconvert.py", package="DNAshapeR")
    load_query_table = system.file ("python", "load_query_table.py", package="DNAshapeR")
    prediction = system.file ("python", "prediction.py", package="DNAshapeR")
    predict_MGW_M = system.file ("python", "predict_MGW_M.py", package="DNAshapeR")
    predict_MGW = system.file ("python", "predict_MGW.py", package="DNAshapeR")
    predict_ProT_M = system.file ("python", "predict_ProT_M.py", package="DNAshapeR")
    predict_ProT = system.file ("python", "predict_ProT.py", package="DNAshapeR")
    predict_Roll_M = system.file ("python", "predict_Roll_M.py", package="DNAshapeR")
    predict_Roll = system.file ("python", "predict_Roll.py", package="DNAshapeR")
    predict_Twist_M = system.file ("python", "predict_Twist_M.py", package="DNAshapeR")
    predict_Twist = system.file ("python", "predict_Twist.py", package="DNAshapeR")
    read_data = system.file ("python", "read_data.py", package="DNAshapeR")
    rev_with_M_and_g = system.file ("python", "rev_with_M_and_g.py", package="DNAshapeR")
    subtract_feature_vector = system.file ("python", "subtract_feature_vector.py", package="DNAshapeR")
    
    python.load(autoconvert)
    python.load(check)
    python.load(hello)
    python.load(load_query_table)
    python.load(prediction)
    python.load(predict_MGW_M)
    python.load(predict_MGW)
    python.load(predict_ProT_M)
    python.load(predict_ProT)
    python.load(predict_Roll_M)
    python.load(predict_Roll)
    python.load(predict_Twist_M)
    python.load(predict_Twist)
    python.load(read_data)
    python.load(rev_with_M_and_g)
    python.load(subtract_feature_vector)
    
    
}
